/**
 * The lookup lists, pulled from FACET's schema and seed files at
 * C:\Projects\facet-crm (scripts/seed/*.ts, src/db/schema.ts enums,
 * messages/*.json labels) and reshaped by SPEC §3 (pinned orders, Other last,
 * Online and WhatsApp split, no Contractor/Architect source).
 *
 * This module is DATA only. `seed-demo.ts` writes it; nothing here touches the
 * database. Every list carries English and Arabic.
 */
import facet from "./facet-lookups.json" with { type: "json" };

export type Bilingual = { en: string; ar: string };

// ---- suppliers, classes, fire ratings, thicknesses ---------------------------
// FACET: products.ts. "The code is the name" — no factory names exist (17 §1).
export const SUPPLIERS = [
  { code: "N", name: "N" },
  { code: "K", name: "K" },
  { code: "C", name: "C" },
  { code: "D", name: "D" },
] as const;

export const CLASSES = ["A", "B", "A2G1", "A2G2"] as const;

export const FIRE_RATINGS = ["B1", "A2", "Normal"] as const;

// FACET seeded 2–8 mm; only 4, 5, 6 are quoted today (17 §3). 4 is standard.
export const THICKNESSES: { mm: string; active: boolean; standard: boolean }[] = [
  { mm: "2.0", active: false, standard: false },
  { mm: "3.0", active: false, standard: false },
  { mm: "4.0", active: true, standard: true },
  { mm: "5.0", active: true, standard: false },
  { mm: "6.0", active: true, standard: false },
  { mm: "7.0", active: false, standard: false },
  { mm: "8.0", active: false, standard: false },
];

export const STANDARD_WIDTHS = ["1.24", "1.5", "2.0"] as const;
export const STANDARD_LENGTH = "5.8";

// ---- company categories (FACET company-categories.ts, founder's order) --------
export const COMPANY_CATEGORIES: Bilingual[] = [
  { en: "Factory", ar: "مصنع" },
  { en: "Contractor", ar: "مقاول" },
  { en: "Advertising", ar: "دعاية وإعلان" },
  { en: "Real estate", ar: "عقارات" },
  { en: "Owner", ar: "مالك" },
  { en: "Consultant", ar: "استشاري" },
  { en: "Station management", ar: "إدارة محطات" },
  { en: "Workshop", ar: "ورشة" },
  { en: "Personal", ar: "شخصي" },
  { en: "Other", ar: "أخرى" },
];

// ---- lead sources (FACET lead-sources.ts reshaped by SPEC §3) ----------------
export const LEAD_SOURCES: Bilingual[] = [
  { en: "Field visit", ar: "زيارة ميدانية" },
  { en: "Direct contact", ar: "اتصال مباشر" },
  { en: "Referral", ar: "ترشيح" },
  { en: "Exhibition", ar: "معرض" },
  { en: "Marketing", ar: "تسويق" },
  { en: "Online", ar: "إنترنت" },
  { en: "WhatsApp", ar: "واتساب" },
  { en: "Other", ar: "أخرى" },
];

// ---- shipment methods (FACET enum shipment_method + messages labels) ---------
export const SHIPMENT_METHODS: { code: string; en: string; ar: string }[] = [
  { code: "ct", en: "CT — the customer's own truck", ar: "CT — شاحنة العميل" },
  { code: "tt", en: "TT — a Technopanel truck", ar: "TT — شاحنة تكنوبانل" },
  { code: "cargo", en: "Cargo — a third party", ar: "Cargo — طرف ثالث" },
];

// ---- contact positions (FACET had free text only; SPEC D21) -------------------
export const POSITIONS: Bilingual[] = [
  { en: "Owner", ar: "المالك" },
  { en: "General manager", ar: "المدير العام" },
  { en: "Project manager", ar: "مدير المشاريع" },
  { en: "Procurement", ar: "المشتريات" },
  { en: "Engineer", ar: "مهندس" },
  { en: "Site engineer", ar: "مهندس موقع" },
  { en: "Architect", ar: "مهندس معماري" },
  { en: "Consultant", ar: "استشاري" },
  { en: "Accountant", ar: "محاسب" },
  { en: "Other", ar: "أخرى" },
];

// ---- countries -------------------------------------------------------------
// FACET's nine keep FACET's Arabic spellings; the six Gulf states are pinned in
// SPEC §3 order. The rest of the ISO list is generated by seed-demo.ts from
// Intl.DisplayNames (en, ar) and sorted alphabetically after the pinned ones.
export const COUNTRIES_FACET: { code: string; en: string; ar: string }[] = [
  { code: "SA", en: "Saudi Arabia", ar: "السعودية" },
  { code: "AE", en: "United Arab Emirates", ar: "الإمارات" },
  { code: "BH", en: "Bahrain", ar: "البحرين" },
  { code: "KW", en: "Kuwait", ar: "الكويت" },
  { code: "QA", en: "Qatar", ar: "قطر" },
  { code: "OM", en: "Oman", ar: "عُمان" },
  { code: "EG", en: "Egypt", ar: "مصر" },
  { code: "JO", en: "Jordan", ar: "الأردن" },
  { code: "SY", en: "Syria", ar: "سوريا" },
];
export const PINNED_COUNTRIES = ["SA", "AE", "BH", "KW", "QA", "OM"];

// ---- cities (FACET cities.ts: 171 Saudi cities, en + ar) ----------------------
export const CITIES: { en: string; ar: string; region: string }[] = facet.cities.map((c) => ({
  en: c.en,
  ar: c.ar,
  region: c.region,
}));
// SPEC §3 pinned order. FACET spells Khobar "Al Khobar".
export const PINNED_CITIES = ["Riyadh", "Jeddah", "Dammam", "Al Khobar", "Makkah", "Madinah"];

// ---- the log's channels (enum in schema; labels from FACET messages) ----------
export const CHANNELS: { code: "visit" | "call" | "whatsapp" | "other"; en: string; ar: string }[] = [
  { code: "visit", en: "Visit", ar: "زيارة" },
  { code: "call", en: "Call", ar: "اتصال" },
  { code: "whatsapp", en: "WhatsApp", ar: "واتساب" },
  { code: "other", en: "Other", ar: "أخرى" },
];
